from Pages.BasePage import BasePage
from Config.config import TestData
from Pages.GalleriesPage import GalleriesPage
from selenium.webdriver.common.by import By
import time
import pyautogui

class PhotonWizard(BasePage):
    CREATE_GALLERY_MAIN_LINK = (By.XPATH, "/html/body/div[1]/div[1]/div[2]/ul[3]/li/div")
    CREATE_GALLERY_MAIN_LINK_ARROW = (By.XPATH, "/html/body/div[1]/div[1]/div[2]/ul[3]/li/div/div/i")
    GALLERY_FROM_TEMPLATE = (By.XPATH,"/html/body/div[1]/div[1]/div[2]/ul[3]/li/div/div/ul/li[2]/a")
    PHOTON_PLAYER_HOVER = (By.XPATH,"/html/body/div[1]/div[2]/div[3]/div[2]/div[1]/ul/li[3]/div/div[1]")
    PHOTON_PLAYER_CREATE_BUTTON = (By.XPATH,"/html/body/div[1]/div[2]/div[3]/div[2]/div[1]/ul/li[3]/div/div[2]/a")

    PLAYER_COLOR_BUTTON = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[1]/div[1]/div[4]/p")
    PLAYER_COLOR_INPUT = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[1]/div[1]/div[4]/div[2]/div/div/div/div[1]/input")
    PLAYER_COLOR_INPUT_DONE = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[1]/div[1]/div[4]/div[1]")

    GALLERY_PAGE_MAIN_LINK = (By.XPATH,"/html/body/div[1]/div[1]/ul/li[1]")
    CUSTOMIZE_GALLERY_GEAR_ICON = (By.XPATH,"/html/body/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[1]/div[2]/a[1]/i")
    ENABLE_VIDEO_CHAPTERS_TOGGLE_BUTTON = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[1]/div[1]/div[5]/p")
    MAIN_SAVE_AND_NEXT_BUTTON = (By.XPATH,"/html/body/div[1]/div[2]/div[1]/div/div[4]/button[2]")
    TEST_GALLERY = (By.XPATH,"/html/body/div[1]/div[2]/div[3]/table/tbody/tr[1]/td[1]/div[1]/div")

    VIDEO_POPUP_TOGGLE_BUTTON = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[3]/div[1]/div[1]/div[3]")
    VIDEO_POPUP_OPTION_THUMBNAIL = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[3]/div[1]/div[1]/div[2]/div/div[1]/div/div/ul/li[2]/label/b")
    VIDEO_POPUP_OPTION_TEXT = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[3]/div[1]/div[1]/div[2]/div/div[1]/div/div/ul/li[3]/label")
    VIDEO_POPUP_ARROW_DOWN = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[3]/div[1]/div[1]/p/div/span")
    VIDEO_POPUP_DONE = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[3]/div[1]/div[1]/div[1]")
    VIDEO_THUMBNAIL = (By.XPATH,"/html/body/div[1]/div/div/div/div/div[1]/div/div/div/div[1]")
    VIDEO_THUMBNAIL_OPEN_VIDEO = (By.XPATH,"/html/body/div[3]/div/div/div[1]/div[2]/div[1]/div[1]/div/div[1]/video")
    VIDEO_THUMBNAIL_OPEN_TEXT = (By.XPATH,"/html/body/div[1]/div/div/div/div/div[1]/p")

    AUTOPLAY_POPUP_ARROW_DOWN = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[3]/div[1]/div[2]/p/div/span")
    START_ON_MUTE_RADIO = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[3]/div[1]/div[2]/div[2]/div/div/div/div/ul/li[2]/label/b")
    AUTOPLAY_WITH_SOUND = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[3]/div[1]/div[2]/div[2]/div/div/div/div/ul/li[3]/label/b")
    AUTOPLAY_WHEN_SCROLL = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[3]/div[1]/div[2]/div[2]/div/div/div/div/ul/li[4]/label/b")
    VIDEO_AUTOPLAY_DONE = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[3]/div[1]/div[2]/div[1]")

    LEAD_GEN_TOGGLE_BUTTON = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[4]/div[1]/div[1]/div[3]/label")
    LEAD_GEN_BTN_ARROW = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[4]/div[1]/div[1]/p/div/span")
    SHOW_AFTER_FIRST_VIDEO_RADIO = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[4]/div[1]/div[1]/div[2]/div/div[2]/div/div[1]/div/ul/li[2]/label/b")
    LEAD_GEN_DONE = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[4]/div[1]/div[1]/div[1]")
    SHOW_BEFORE_FIRST_VIDEO_RADIO = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[4]/div[1]/div[1]/div[2]/div/div[2]/div/div[1]/div/ul/li[3]/label/b")
    VIDEO_PLAYER_SIZE = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[6]/div[1]/div[1]/p/div/span")
    VIDEO_PLAYER_SIZE_RADIO = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[6]/div[1]/div[1]/div[2]/div/div/div/div/ul/li[2]/label/b")
    VIDEO_PLAYER_SIZE_WIDTH = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[6]/div[1]/div[1]/div[2]/div/div/div/div/ul/li[2]/label/input[2]")
    VIDEO_PLAYER_SIZE_LENGTH = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[6]/div[1]/div[1]/div[2]/div/div/div/div/ul/li[2]/label/input[3]")
    VIDEO_PLAYER_SIZE_DONE = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[6]/div[1]/div[1]/div[1]")

    PLAY_VIDEO_LOOP_MODE_TOGGLE = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[3]/div[1]/div[3]/div[3]/label")
    PLAY_VIDEO_LOOP_MODE_DONE = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[3]/div[1]/div[3]/div[1]")

    PASSWORD_PROTECTION_TOGGLE = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[5]/div[1]/div[1]/div[3]/label/span")
    PASSWORD_INPUT = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[5]/div[1]/div[1]/div[2]/div/div[1]/div/input")
    PASSWORD_TEXT_INPUT = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[5]/div[1]/div[1]/div[2]/div/div[2]/div/textarea")
    PASSWORD_PROTECTION_DONE = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[5]/div[1]/div[1]/div[1]")
    IFRAME_PASSWORD_INPUT =(By.XPATH, "/html/body/div/div/div/div/div/div/div[1]/div/div[1]/input")
    IFRAME_PASSWORD_INPUT_CONTINUE = (By.XPATH,"/html/body/div/div/div/div/div/div/div[1]/div/div[2]/a")

    ALLOW_DOWNLOADING_TOGGLE_BUTTON = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[5]/div[1]/div[2]/div[3]/label/span")

    BRAND_PLAYER_TOGGLE_BUTTON = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[6]/div[1]/div[4]/div[3]/label/span")
    REPLACE_LOGO_BUTTON = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[6]/div[1]/div[4]/div[2]/div/div[3]/div/div/div[2]/button")
    CHOOSE_TO_UPLOAD_FILE = (By.XPATH,"/html/body/div[4]/div/div/div/div[2]/div/div/div/div/div[1]/button")
    FILE_PATH = ("C:\\Users\\User\\Downloads\\alien_budgers.png")
    BRAND_PLAYER_DONE = (By.XPATH,'/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[6]/div[1]/div[4]/div[1]')
    PLAYER_CENTER = (By.CSS_SELECTOR, ".mejs-overlay-button")

    VIDEO_WATERMARK_TOGGLE_BUTTON = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[6]/div[1]/div[5]/div[3]/label/span")
    BOTTOM_RIGHT_RADIO = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[6]/div[1]/div[5]/div[2]/div/div[1]/div/div/ul/li[2]/label/i")
    BOTTOM_LEFT_RADIO = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[6]/div[1]/div[5]/div[2]/div/div[1]/div/div/ul/li[3]/label/i")
    TOP_RIGHT_RADIO = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[6]/div[1]/div[5]/div[2]/div/div[1]/div/div/ul/li[4]/label/i")
    VIDEO_WATERMARK_DONE = (By.XPATH,"/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[6]/div[1]/div[5]/div[1]")





    def __init__(self,driver):
        super().__init__(driver)
        self.driver.get(TestData.BASE_URL)
    def create_photon_wizard(self):
        self.do_hover(self.CREATE_GALLERY_MAIN_LINK_ARROW)
        time.sleep(2)
        self.do_click(self.GALLERY_FROM_TEMPLATE)
        time.sleep(2)
        self.do_hover(self.PHOTON_PLAYER_HOVER)
        time.sleep(2)
        self.do_click(self.PHOTON_PLAYER_CREATE_BUTTON)
        time.sleep(3)
    def customize_save_galleries(self):
        self.do_click(self.GALLERY_PAGE_MAIN_LINK)
        time.sleep(2)
        self.do_click(self.TEST_GALLERY)
        time.sleep(2)
    def change_player_color(self):
        time.sleep(2)
        self.do_click(self.PLAYER_COLOR_BUTTON)
        time.sleep(2)
        self.do_click(self.PLAYER_COLOR_INPUT)
        time.sleep(2)
        self.do_clear(self.PLAYER_COLOR_INPUT)
        time.sleep(2)
        self.do_send_keys(self.PLAYER_COLOR_INPUT,"#0892dd")
        time.sleep(2)
        self.do_click(self.PLAYER_COLOR_INPUT_DONE)
    def enable_video_chapters(self):
        self.do_click(self.GALLERY_PAGE_MAIN_LINK)
        self.do_click(self.CUSTOMIZE_GALLERY_GEAR_ICON)
        time.sleep(3)
        elem = self.driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[1]/div[1]/div[5]/p')
        elem.click()
        time.sleep(5)
        iframe = self.driver.find_element(By.ID,"simulator_content")
        self.driver.switch_to.frame(iframe)
        time.sleep(2)
        # chapters_wrap = self.driver.find_element(By.XPATH, "/html/body/div[1]/div/div/div/div/div[1]/div[2]/div[1]/div[1]/div/div[2]/div[9]")
        # chapters_wrap_text = chapters_wrap.text
        # print(chapters_wrap_text)
        # self.do_click(self.MAIN_SAVE_AND_NEXT_BUTTON)
        # time.sleep(5)
        # self.do_click(self.GALLERY_PAGE_MAIN_LINK)
        # time.sleep(5)
        # self.do_click(self.TEST_GALLERY)
        # time.sleep(2)
        # new_page = self.driver.window_handles[1]
        # self.driver.switch_to.window(new_page)
        # time.sleep(2)
    def disable_video_chapters(self):
        self.do_click(self.GALLERY_PAGE_MAIN_LINK)
        self.do_click(self.CUSTOMIZE_GALLERY_GEAR_ICON)
        elem = self.driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div[8]/div[1]/div/ul/li[1]/div[1]/div[5]/div[3]')
        if elem.is_enabled():
            elem.click()
            time.sleep(2)
        else:
            pass
        time.sleep(2)
        iframe = self.driver.find_element(By.ID, "simulator_content")
        self.driver.switch_to.frame(iframe)
        time.sleep(2)

    def video_popup(self):
        self.do_click(self.GALLERY_PAGE_MAIN_LINK)
        self.do_click(self.CUSTOMIZE_GALLERY_GEAR_ICON)
        time.sleep(2)
        self.do_click(self.VIDEO_POPUP_ARROW_DOWN)
        time.sleep(2)
        self.do_click(self.VIDEO_POPUP_OPTION_THUMBNAIL)
        time.sleep(2)
        self.do_click(self.VIDEO_POPUP_DONE)
        iframe = self.driver.find_element(By.ID, "simulator_content")
        self.driver.switch_to.frame(iframe)
        time.sleep(2)
    def text_popup(self):
        self.do_click(self.GALLERY_PAGE_MAIN_LINK)
        self.do_click(self.CUSTOMIZE_GALLERY_GEAR_ICON)
        time.sleep(2)
        self.do_click(self.VIDEO_POPUP_ARROW_DOWN)
        time.sleep(2)
        self.do_click(self.VIDEO_POPUP_OPTION_TEXT)
        time.sleep(2)
        self.do_click(self.VIDEO_POPUP_DONE)
        time.sleep(2)
        iframe = self.driver.find_element(By.ID, "simulator_content")
        self.driver.switch_to.frame(iframe)
        time.sleep(3)

    def video_autoplay(self):
        self.do_click(self.GALLERY_PAGE_MAIN_LINK)
        self.do_click(self.CUSTOMIZE_GALLERY_GEAR_ICON)
        time.sleep(2)
        self.do_click(self.AUTOPLAY_POPUP_ARROW_DOWN)
        time.sleep(2)
        self.do_click(self.START_ON_MUTE_RADIO)
        time.sleep(2)
        self.do_click(self.VIDEO_AUTOPLAY_DONE)
        time.sleep(2)
        iframe = self.driver.find_element(By.ID, "simulator_content")
        self.driver.switch_to.frame(iframe)
        time.sleep(3)

    def video_autoplay_with_sound(self):
        self.do_click(self.GALLERY_PAGE_MAIN_LINK)
        self.do_click(self.CUSTOMIZE_GALLERY_GEAR_ICON)
        time.sleep(2)
        self.do_click(self.AUTOPLAY_POPUP_ARROW_DOWN)
        time.sleep(2)
        self.do_click(self.AUTOPLAY_WITH_SOUND)
        time.sleep(2)
        self.do_click(self.VIDEO_AUTOPLAY_DONE)
        time.sleep(2)
        iframe = self.driver.find_element(By.ID, "simulator_content")
        self.driver.switch_to.frame(iframe)
        time.sleep(3)
    def video_autoplay_scroll_view(self):
        self.do_click(self.GALLERY_PAGE_MAIN_LINK)
        self.do_click(self.CUSTOMIZE_GALLERY_GEAR_ICON)
        time.sleep(2)
        self.do_click(self.AUTOPLAY_POPUP_ARROW_DOWN)
        time.sleep(2)
        self.do_click(self.AUTOPLAY_WITH_SOUND)
        time.sleep(2)
        self.do_click(self.VIDEO_AUTOPLAY_DONE)
        time.sleep(2)
        self.do_click(self.MAIN_SAVE_AND_NEXT_BUTTON)
        time.sleep(2)
        self.customize_save_galleries()
    def play_video_loop_mode(self):
        self.do_click(self.GALLERY_PAGE_MAIN_LINK)
        self.do_click(self.CUSTOMIZE_GALLERY_GEAR_ICON)
        time.sleep(2)
        self.do_click(self.PLAY_VIDEO_LOOP_MODE_TOGGLE)
        time.sleep(2)
        self.do_click(self.PLAY_VIDEO_LOOP_MODE_DONE)
        time.sleep(2)
        iframe = self.driver.find_element(By.ID, "simulator_content")
        self.driver.switch_to.frame(iframe)
        time.sleep(3)
    def lead_gen_after_first_video(self):
        self.do_click(self.GALLERY_PAGE_MAIN_LINK)
        self.do_click(self.CUSTOMIZE_GALLERY_GEAR_ICON)
        time.sleep(2)
        self.do_click(self.LEAD_GEN_TOGGLE_BUTTON)
        time.sleep(2)
        self.do_click(self.SHOW_AFTER_FIRST_VIDEO_RADIO)
        time.sleep(3)
        print(pyautogui.position())
        time.sleep(2)
        pyautogui.click(486,851)
        self.do_click(self.LEAD_GEN_DONE)
        time.sleep(2)
        self.do_click(self.VIDEO_PLAYER_SIZE)
        time.sleep(2)
        self.do_click(self.VIDEO_PLAYER_SIZE_RADIO)
        time.sleep(2)
        self.do_clear(self.VIDEO_PLAYER_SIZE_WIDTH)
        time.sleep(1)
        self.do_send_keys(self.VIDEO_PLAYER_SIZE_WIDTH,"1100")
        time.sleep(2)
        self.do_clear(self.VIDEO_PLAYER_SIZE_LENGTH)
        self.do_send_keys(self.VIDEO_PLAYER_SIZE_LENGTH,"618")
        time.sleep(2)
        self.do_click(self.VIDEO_PLAYER_SIZE_DONE)
        time.sleep(2)
        iframe = self.driver.find_element(By.ID, "simulator_content")
        self.driver.switch_to.frame(iframe)
        time.sleep(3)
    def lead_gen_before_first_video(self):
        self.do_click(self.GALLERY_PAGE_MAIN_LINK)
        self.do_click(self.CUSTOMIZE_GALLERY_GEAR_ICON)
        time.sleep(2)
        self.do_click(self.LEAD_GEN_TOGGLE_BUTTON)
        time.sleep(2)
        self.do_click(self.SHOW_BEFORE_FIRST_VIDEO_RADIO)
        time.sleep(3)
        print(pyautogui.position())
        time.sleep(2)
        pyautogui.click(486,851)
        self.do_click(self.LEAD_GEN_DONE)
        time.sleep(2)
        iframe = self.driver.find_element(By.ID, "simulator_content")
        self.driver.switch_to.frame(iframe)
        time.sleep(3)
    def password_protection(self):
        self.do_click(self.GALLERY_PAGE_MAIN_LINK)
        self.do_click(self.CUSTOMIZE_GALLERY_GEAR_ICON)
        time.sleep(2)
        pyautogui.click(486, 851)
        time.sleep(2)
        self.do_click(self.PASSWORD_PROTECTION_TOGGLE)
        time.sleep(2)
        self.do_clear(self.PASSWORD_INPUT)
        time.sleep(2)
        self.do_send_keys(self.PASSWORD_INPUT,"abcdefg")
        time.sleep(2)
        self.do_clear(self.PASSWORD_TEXT_INPUT)
        time.sleep(2)
        self.do_send_keys(self.PASSWORD_TEXT_INPUT,"higklmnop")
        time.sleep(2)
        self.do_click(self.PASSWORD_PROTECTION_DONE)
        time.sleep(2)
        iframe = self.driver.find_element(By.ID, "simulator_content")
        self.driver.switch_to.frame(iframe)
        time.sleep(3)
    def allow_downloading(self):
        self.do_click(self.GALLERY_PAGE_MAIN_LINK)
        self.do_click(self.CUSTOMIZE_GALLERY_GEAR_ICON)
        time.sleep(2)
        pyautogui.click(486, 851)
        time.sleep(2)
        self.do_click(self.ALLOW_DOWNLOADING_TOGGLE_BUTTON)
        time.sleep(2)
        iframe = self.driver.find_element(By.ID, "simulator_content")
        self.driver.switch_to.frame(iframe)
        time.sleep(3)
    def brand_player_with_logo(self):
        self.do_click(self.GALLERY_PAGE_MAIN_LINK)
        self.do_click(self.CUSTOMIZE_GALLERY_GEAR_ICON)
        time.sleep(2)
        pyautogui.click(486, 851)
        time.sleep(2)
        self.do_click(self.BRAND_PLAYER_TOGGLE_BUTTON)
        time.sleep(2)
        self.do_click(self.REPLACE_LOGO_BUTTON)
        time.sleep(2)
        self.do_click(self.CHOOSE_TO_UPLOAD_FILE)
        time.sleep(3)
        pyautogui.typewrite(self.FILE_PATH, interval=0.15)
        pyautogui.press('enter')
        time.sleep(8)
        self.do_click(self.BRAND_PLAYER_DONE)
        iframe = self.driver.find_element(By.ID, "simulator_content")
        self.driver.switch_to.frame(iframe)
        time.sleep(3)
    def video_watermark_bottom_right(self):
        self.do_click(self.GALLERY_PAGE_MAIN_LINK)
        self.do_click(self.CUSTOMIZE_GALLERY_GEAR_ICON)
        time.sleep(2)
        pyautogui.click(486, 851)
        time.sleep(2)
        self.do_click(self.VIDEO_WATERMARK_TOGGLE_BUTTON)
        time.sleep(2)
        self.do_click(self.BOTTOM_RIGHT_RADIO)
        time.sleep(2)
        self.do_click(self.VIDEO_WATERMARK_DONE)
        iframe = self.driver.find_element(By.ID, "simulator_content")
        self.driver.switch_to.frame(iframe)
        time.sleep(4)
    def video_watermark_bottom_left(self):
        self.do_click(self.GALLERY_PAGE_MAIN_LINK)
        self.do_click(self.CUSTOMIZE_GALLERY_GEAR_ICON)
        time.sleep(2)
        pyautogui.click(486, 851)
        time.sleep(2)
        self.do_click(self.VIDEO_WATERMARK_TOGGLE_BUTTON)
        time.sleep(2)
        self.do_click(self.BOTTOM_LEFT_RADIO)
        time.sleep(2)
        self.do_click(self.VIDEO_WATERMARK_DONE)
        iframe = self.driver.find_element(By.ID, "simulator_content")
        self.driver.switch_to.frame(iframe)
        time.sleep(4)

    def video_watermark_top_right(self):
        self.do_click(self.GALLERY_PAGE_MAIN_LINK)
        self.do_click(self.CUSTOMIZE_GALLERY_GEAR_ICON)
        time.sleep(2)
        pyautogui.click(486, 851)
        time.sleep(2)
        self.do_click(self.VIDEO_WATERMARK_TOGGLE_BUTTON)
        time.sleep(2)
        self.do_click(self.TOP_RIGHT_RADIO)
        time.sleep(2)
        self.do_click(self.VIDEO_WATERMARK_DONE)
        iframe = self.driver.find_element(By.ID, "simulator_content")
        self.driver.switch_to.frame(iframe)
        time.sleep(4)





